import React from 'react'
import {
  AbsoluteFill,
  Audio,
  Sequence,
  useCurrentFrame,
  useVideoConfig,
  interpolate,
  Easing
} from 'remotion'
import { VideoSettings, TranscriptSegment, VideoAsset } from '@/types'
import { Caption } from '../components/Caption'
import { BackgroundMedia } from '../components/BackgroundMedia'

export interface YouTubeVideoProps {
  audioUrl: string
  transcript: TranscriptSegment[]
  assets: VideoAsset[]
  settings: VideoSettings
  title?: string
}

export const YouTubeVideo: React.FC<YouTubeVideoProps> = ({
  audioUrl,
  transcript,
  assets,
  settings,
  title
}) => {
  const frame = useCurrentFrame()
  const { fps, durationInFrames } = useVideoConfig()
  const currentTime = frame / fps

  // タイトル表示の制御（最初の3秒間）
  const showTitle = currentTime < 3
  const titleOpacity = interpolate(
    frame,
    [0, fps * 0.5, fps * 2.5, fps * 3],
    [0, 1, 1, 0],
    {
      extrapolateLeft: 'clamp',
      extrapolateRight: 'clamp',
      easing: Easing.bezier(0.25, 0.1, 0.25, 1)
    }
  )

  // 現在のキャプションを取得
  const currentCaption = transcript.find(
    segment => currentTime >= segment.startTime && currentTime <= segment.endTime
  )

  // 現在の背景アセットを取得
  const getCurrentAsset = (): VideoAsset | undefined => {
    // アセットの切り替えロジック（10秒ごとまたはシーン変更時）
    const assetIndex = Math.floor(currentTime / 10) % assets.length
    return assets[assetIndex]
  }

  const currentAsset = getCurrentAsset()

  return (
    <AbsoluteFill style={{ backgroundColor: settings.backgroundColor || '#000000' }}>
      {/* 音声トラック */}
      <Audio src={audioUrl} />
      
      {/* 背景メディア */}
      {currentAsset && (
        <BackgroundMedia
          asset={currentAsset}
          settings={settings}
        />
      )}
      
      {/* オーバーレイ（グラデーション） */}
      <AbsoluteFill
        style={{
          background: 'linear-gradient(to bottom, rgba(0,0,0,0.3) 0%, rgba(0,0,0,0.1) 50%, rgba(0,0,0,0.6) 100%)'
        }}
      />
      
      {/* タイトル表示 */}
      {showTitle && title && (
        <AbsoluteFill
          style={{
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'center',
            opacity: titleOpacity
          }}
        >
          <div
            style={{
              fontSize: 64,
              fontWeight: 'bold',
              color: '#ffffff',
              textAlign: 'center',
              textShadow: '2px 2px 4px rgba(0,0,0,0.8)',
              padding: '20px',
              backgroundColor: 'rgba(0,0,0,0.5)',
              borderRadius: '10px',
              maxWidth: '80%'
            }}
          >
            {title}
          </div>
        </AbsoluteFill>
      )}
      
      {/* キャプション */}
      {currentCaption && (
        <Caption
          text={currentCaption.text}
          style={settings.captionStyle}
          position="bottom"
        />
      )}
      
      {/* ブランディング（右下角） */}
      <AbsoluteFill
        style={{
          display: 'flex',
          alignItems: 'flex-end',
          justifyContent: 'flex-end',
          padding: '20px'
        }}
      >
        <div
          style={{
            fontSize: 16,
            color: '#ffffff',
            backgroundColor: 'rgba(0,0,0,0.7)',
            padding: '8px 12px',
            borderRadius: '20px',
            textShadow: '1px 1px 2px rgba(0,0,0,0.8)'
          }}
        >
          Generated by StandFM2Movie
        </div>
      </AbsoluteFill>
    </AbsoluteFill>
  )
}